kind: Service
apiVersion: v1
metadata:
  name: counter-backend
  labels:
    app: counter-app
    app.kubernetes.io/part-of: counter-app
spec:
  ports:
    - name: counter-backend
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: counter-backend
